### PR TITLE
kong 0.10 changes + possible bug fix ( to verify )

### PR DESCRIPTION
**Pull request by maksimlikharev**
1. kong 0.10 changes
2. I think there is a mistake and "Try It" should point to a wicked location vs kong endpoint, it doesn't work the way it is

### CODE REVIEW

**Comment by DonMartin76** [comment]
The "Try It!" should work like that; there's a predefined API mapping /swagger-ui from the API Gateway to the same end point of the portal; this is done like this to make sure we don't run into cross origin issues when doing API calls from the browser. Otherwise the API would need explicit CORS support, like this it doesn't, as the origin of the call is the API gateway host. If it doesn't work correctly, something else is off. What kind of issue does this have?

**Comment by maksimlikharev** [comment]
I think there is a confusion of how that works.

change was:
  **- a(href='#{glob.network.schema}://#{glob.network.apiHost}/swagger-ui/...**
  **+ a(href='#{glob.network.schema}://#{glob.network.portalHost}/swagger-ui/...**

in reality it should be:

**a(href='/swagger-ui...**

glob.network.apiHost = kong
glob.network.portalHost = wicked

"Try it" should load swagger definition from wicked portal, where that belongs and execute REST API from kong. Otherwise it will try to load swagger from kong and fail.

**Comment by DonMartin76** [comment]
No confusion there I think. /swagger-ui should work both directly from the portal and via Kong. This routing via Kong is configured in the adapter to avoid doing CORS calls from Swagger UI. Try Me retrieved the JSON from the Portal via a CORS call.

**Comment by maksimlikharev** [comment]
I understand, but whatever you described doesn't work for us, it fails to load swagger from kong. I'll recheck if this is something that we might broke with the kong 10 changes.

On a side note, how we can talk, basically we need your vision/plans on storage (portal-api project), file system approach doesn't work for us, so we need to understand if we can combine our efforts or we will do it by ourself.

**Comment by DonMartin76** [comment]
Does gitter work for you as a starter? I have a lot of design docs up and coming right now, also covering a replacement for the JSON files (with Mongo). Let's connect on gitter and chat about that at times. Which time zone are you in?

**Comment by DonMartin76** [comment]
What kind of issue do you still have with the "Try it" button? How does it behave (or not behave)? @DanielHWe filed the following issue the other day: Haufe-Lexware/wicked.haufe.io#85, might it be the same, or something similar?

Closing this for now, the Kong changes are in the repo branch `feat/kong-0.11`, where I would kindly ask you to do a review.

**Pull request closed without merging**
